apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shortname" . }}
  namespace: {{ .Values.Namespace | default "default" }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
